version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin       # Usuario de la base de datos
      POSTGRES_PASSWORD: secret  # Contrase√±a del usuario
      POSTGRES_DB: mydatabase    # Nombre de la base de datos
    ports:
      - "5432:5432"              # Exponer el puerto para conexiones externas
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistir los datos

volumes:
  postgres_data:
    driver: local
